apiVersion: apps/v1
kind: Deployment
metadata:
  name: php-apache-environment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: php-apache-environment
  template:
    metadata:
      labels:
        app: php-apache-environment
    spec:
      containers:
        - name: php-apache
          image: nattaponpongkaop/os-php-new:demo
          volumeMounts:
            - name: php-volume
              mountPath: /var/www/html
          ports:
            - containerPort: 80
      volumes:
        - name: php-volume
          hostPath:
            path: /path/to/php/src
      restartPolicy: Always
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
        - name: db
          image: mysql
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: MYSQL_ROOT_PASSWORD
            - name: MYSQL_DATABASE
              value: MYSQL_DATABASE
            - name: MYSQL_USER
              value: MYSQL_USER
            - name: MYSQL_PASSWORD
              value: MYSQL_PASSWORD
          ports:
            - containerPort: 3306
          volumeMounts:
            - name: db-data
              mountPath: /var/lib/mysql
      volumes:
        - name: db-data
          emptyDir: {}
      restartPolicy: Always
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: phpmyadmin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: phpmyadmin
  template:
    metadata:
      labels:
        app: phpmyadmin
    spec:
      containers:
        - name: phpmyadmin
          image: phpmyadmin/phpmyadmin
          env:
            - name: PMA_HOST
              value: db
          ports:
            - containerPort: 80
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: php-apache-environment
spec:
  selector:
    app: php-apache-environment
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  name: db
spec:
  selector:
    app: db
  ports:
    - protocol: TCP
      port: 3306
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: phpmyadmin
spec:
  selector:
    app: phpmyadmin
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
